name: CI/CD Dream Bridge

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
      MISTRAL_API_KEY_IMAGE: ${{ secrets.MISTRAL_API_KEY_IMAGE }}
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
      GROQ_API_KEY_OLD_HAKIM: ${{ secrets.GROQ_API_KEY_OLD_HAKIM }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Create and activate virtual environment + install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r dream_bridge/requirements.txt

    - name: Run migrations
      run: |
        source venv/bin/activate
        python dream_bridge/manage.py migrate

    - name: Run unit tests
      run: |
        source venv/bin/activate
        python ./dream_bridge/manage.py test ./dream_bridge/dream_bridge_app/

    - name: Lint with Flake8
      run: |
        source venv/bin/activate
        pip install flake8
        flake8 --exclude=migrations

  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
      MISTRAL_API_KEY_IMAGE: ${{ secrets.MISTRAL_API_KEY_IMAGE }}
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
      GROQ_API_KEY_OLD_HAKIM: ${{ secrets.GROQ_API_KEY_OLD_HAKIM }}

    steps:
    - name: Deploy to VPS via SSH
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: ${{ secrets.VPS_PORT }}
        script: |
          cd /home/ubuntu/CICD_TEST/dream_bridge
          git pull origin main
          source venv/bin/activate
          pip install -r dream_bridge/requirements.txt
          python manage.py migrate
          sudo systemctl restart django
          sudo systemctl restart celery
          sudo systemctl restart redis
